import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Animated, Pressable, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Colors } from '../theme/colors';
interface LockOverlayProps{onUnlock:()=>void;showPrompt:boolean;onRequestPrompt:()=>void;}
const HOLD_DURATION_MS=1500;const BUTTON_SIZE=64;
export function LockOverlay({onUnlock,showPrompt,onRequestPrompt}:LockOverlayProps){
  const [isHolding,setIsHolding]=useState(false);const progress=useRef(new Animated.Value(0)).current;const promptAnim=useRef(new Animated.Value(showPrompt?1:0)).current;
  useEffect(()=>{Animated.timing(promptAnim,{toValue:showPrompt?1:0,duration:showPrompt?180:150,useNativeDriver:true}).start();},[promptAnim,showPrompt]);
  const clearHold=useCallback(()=>{progress.stopAnimation();progress.setValue(0);setIsHolding(false);},[progress]);
  const handlePressIn=useCallback(()=>{progress.stopAnimation();progress.setValue(0);setIsHolding(true);Animated.timing(progress,{toValue:1,duration:HOLD_DURATION_MS,useNativeDriver:false}).start();},[progress]);
  useEffect(()=>()=>clearHold(),[clearHold]);
  return <View style={styles.container} pointerEvents="box-none"><Pressable style={StyleSheet.absoluteFillObject} onPress={onRequestPrompt}/><Animated.View pointerEvents={showPrompt?'auto':'none'} style={[styles.unlockWrapper,{opacity:promptAnim,transform:[{translateY:promptAnim.interpolate({inputRange:[0,1],outputRange:[-10,0]})},{scale:promptAnim.interpolate({inputRange:[0,1],outputRange:[.9,1]})}]}]}><TouchableOpacity style={styles.unlockButton} onPress={onRequestPrompt} onLongPress={onUnlock} delayLongPress={HOLD_DURATION_MS} onPressIn={handlePressIn} onPressOut={clearHold} activeOpacity=.85><Animated.View pointerEvents="none" style={[styles.unlockFill,{width:progress.interpolate({inputRange:[0,1],outputRange:[0,BUTTON_SIZE]})}]}/><View pointerEvents="none" style={styles.lockBody}><View style={styles.lockShackle}/></View></TouchableOpacity>{isHolding&&<Text style={styles.label}>Mantén presionado…</Text>}</Animated.View></View>;
}
const styles=StyleSheet.create({container:{...StyleSheet.absoluteFillObject,zIndex:200,elevation:200},unlockWrapper:{position:'absolute',top:18,alignSelf:'center',alignItems:'center'},unlockButton:{width:BUTTON_SIZE,height:BUTTON_SIZE,borderRadius:BUTTON_SIZE/2,backgroundColor:'rgba(0,0,0,.58)',justifyContent:'center',alignItems:'center',overflow:'hidden',elevation:8},unlockFill:{position:'absolute',left:0,top:0,bottom:0,backgroundColor:Colors.accentYellow},lockBody:{width:22,height:18,borderWidth:4,borderColor:Colors.accentYellow,borderRadius:4,marginTop:7},lockShackle:{position:'absolute',width:15,height:14,borderWidth:4,borderBottomWidth:0,borderColor:Colors.accentYellow,borderTopLeftRadius:9,borderTopRightRadius:9,left:0,top:-14},label:{color:'#FFF',fontSize:11,fontFamily:'Montserrat-SemiBold',marginTop:5,backgroundColor:'rgba(0,0,0,.38)',paddingHorizontal:8,paddingVertical:3,borderRadius:8}});
