import React, { useEffect, useRef } from 'react';
import { Animated, FlatList, Image, Modal, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import { BookPage } from '../types/book';
import { Colors } from '../theme/colors';
interface PageIndexOverlayProps{visible:boolean;pages:BookPage[];currentPage:number;onSelectPage:(index:number)=>void;onClose:()=>void;}
const COLUMNS=2;
export function PageIndexOverlay({visible,pages,currentPage,onSelectPage,onClose}:PageIndexOverlayProps){
  const listRef=useRef<FlatList<BookPage>>(null); const {width,height}=useWindowDimensions(); const scale=Math.max(.82,Math.min(1.2,Math.min(width/904,height/407))); const leftInset=165*scale; const rightInset=145*scale; const gap=18*scale; const thumbWidth=(width-leftInset-rightInset-gap)/2; const thumbHeight=thumbWidth/1.48; const rowHeight=thumbHeight+16*scale; const entrance=useRef(new Animated.Value(0)).current; const current=pages[currentPage];
  useEffect(()=>{if(!visible){entrance.setValue(0);return;}entrance.setValue(0);Animated.timing(entrance,{toValue:1,duration:280,useNativeDriver:true}).start();},[entrance,visible]);
  useEffect(()=>{if(!visible||!pages.length)return;const row=Math.floor(currentPage/COLUMNS);const offset=Math.max(0,row*rowHeight-(height-rowHeight)/2);const t=setTimeout(()=>listRef.current?.scrollToOffset({offset,animated:false}),90);return()=>clearTimeout(t);},[visible,currentPage,pages.length,height,rowHeight]);
  return <Modal visible={visible} transparent animationType="none" statusBarTranslucent onRequestClose={onClose}><View style={styles.root}>{current&&<Image source={{uri:current.uri}} style={StyleSheet.absoluteFill} resizeMode="cover" fadeDuration={0}/>}<Animated.View style={[styles.dim,{opacity:entrance}]}/><TouchableOpacity style={[styles.close,{top:18*scale,left:18*scale,width:46*scale,height:46*scale,borderRadius:23*scale}]} onPress={onClose}><Image source={require('../assets/ui/ic_close.png')} style={{width:28*scale,height:28*scale}} resizeMode="contain"/></TouchableOpacity><Animated.View style={[styles.listWrap,{opacity:entrance,transform:[{translateY:entrance.interpolate({inputRange:[0,1],outputRange:[20,0]})}]}]}><FlatList ref={listRef} data={pages} keyExtractor={item=>`index-${item.pageNumber}-${item.uri}`} numColumns={COLUMNS} showsVerticalScrollIndicator={false} removeClippedSubviews={false} initialNumToRender={8} windowSize={7} columnWrapperStyle={{gap}} contentContainerStyle={{paddingTop:44*scale,paddingLeft:leftInset,paddingRight:rightInset,paddingBottom:36*scale,gap:16*scale}} renderItem={({item,index})=><Thumb item={item} active={index===currentPage} width={thumbWidth} height={thumbHeight} scale={scale} onPress={()=>onSelectPage(index)}/>} /></Animated.View></View></Modal>;
}
function Thumb({item,active,width,height,scale,onPress}:{item:BookPage;active:boolean;width:number;height:number;scale:number;onPress:()=>void}){return <TouchableOpacity style={[styles.thumb,{width,height,borderWidth:active?4*scale:0},active&&styles.active]} onPress={onPress}><Image key={item.uri} source={{uri:item.uri}} style={StyleSheet.absoluteFill} resizeMode="cover" fadeDuration={0}/><View style={[styles.ribbonWrap,{left:10*scale,width:48*scale,height:60*scale}]}><Image source={require('../assets/ui/ic_page_mark.png')} style={StyleSheet.absoluteFill} resizeMode="stretch"/><Text style={[styles.number,{fontSize:19*scale,top:8*scale}]}>{item.pageNumber}</Text></View></TouchableOpacity>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#101020'},dim:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'rgba(8,6,10,.70)'},listWrap:{flex:1},close:{position:'absolute',zIndex:20,backgroundColor:'#F3F4EA',justifyContent:'center',alignItems:'center',elevation:8},thumb:{overflow:'hidden',backgroundColor:'#222',borderColor:'#FFF'},active:{borderColor:'#FFF'},ribbonWrap:{position:'absolute',top:0,alignItems:'center'},number:{position:'absolute',color:Colors.bookPagesText,fontFamily:'Montserrat-ExtraBold'},});
