/**
 * Static require() registry for every bundled cover image.
 * React Native/Metro can only include assets referenced through static paths.
 */

const covers: Record<string, number> = {
  ADayInReverse: require('./covers/ADayInReverse.webp'),
  AFunWalk: require('./covers/AFunWalk.webp'),
  AGoodIdea: require('./covers/AGoodIdea.webp'),
  AGreatFriendship: require('./covers/AGreatFriendship.webp'),
  ALittleAntsBigJob: require('./covers/ALittleAntsBigJob.webp'),
  APerfectHome: require('./covers/APerfectHome.webp'),
  AllIsNotLost: require('./covers/AllIsNotLost.webp'),
  Belka: require('./covers/Belka.webp'),
  BirdsChoir: require('./covers/BirdsChoir.webp'),
  BraveEaglet: require('./covers/BraveEaglet.webp'),
  BuyMeSomethingMom: require('./covers/BuyMeSomethingMom.webp'),
  ChangeCanBeGood: require('./covers/ChangeCanBeGood.webp'),
  Cow: require('./covers/Cow.webp'),
  Dolphin: require('./covers/Dolphin.webp'),
  DontCockYourNose: require('./covers/DontCockYourNose.webp'),
  FamilyLove: require('./covers/FamilyLove.webp'),
  Farm: require('./covers/Farm.webp'),
  FavorableFriendship: require('./covers/FavorableFriendship.webp'),
  Firefly: require('./covers/Firefly.webp'),
  ForestSchool: require('./covers/ForestSchool.webp'),
  Friendship: require('./covers/Friendship.webp'),
  FruitKingdom: require('./covers/FruitKingdom.webp'),
  GoodWeather: require('./covers/GoodWeather.webp'),
  GrasshoppersGift: require('./covers/GrasshoppersGift.webp'),
  GrowingAGarden: require('./covers/GrowingAGarden.webp'),
  Gvozdik: require('./covers/Gvozdik.webp'),
  HomeWhereTheHeartIs: require('./covers/HomeWhereTheHeartIs.webp'),
  HowToFindAFriend: require('./covers/HowToFindAFriend.webp'),
  Hvol: require('./covers/Hvol.webp'),
  ImaginaryIsland: require('./covers/ImaginaryIsland.webp'),
  Lamb: require('./covers/Lamb.webp'),
  LateToTheParty: require('./covers/LateToTheParty.webp'),
  LetsPlayTogether: require('./covers/LetsPlayTogether.webp'),
  LittleTigerFightsMicrobes: require('./covers/LittleTigerFightsMicrobes.webp'),
  LonelyPuppy: require('./covers/LonelyPuppy.webp'),
  MagicChristmasTree: require('./covers/MagicChristmasTree.webp'),
  MonkeysLesson: require('./covers/MonkeysLesson.webp'),
  Mouse: require('./covers/Mouse.webp'),
  MrSquirrelsHome: require('./covers/MrSquirrelsHome.webp'),
  MyDadIsAGiant: require('./covers/MyDadIsAGiant.webp'),
  MysteriousSickness: require('./covers/MysteriousSickness.webp'),
  NewFriends: require('./covers/NewFriends.webp'),
  NightSecret: require('./covers/NightSecret.webp'),
  OhCrumbs: require('./covers/OhCrumbs.webp'),
  Panda: require('./covers/Panda.webp'),
  PandaExcuse: require('./covers/PandaExcuse.webp'),
  PlanetsUnion: require('./covers/PlanetsUnion.webp'),
  PoleStar: require('./covers/PoleStar.webp'),
  Puddle: require('./covers/Puddle.webp'),
  ResponsibilityIsTheKey: require('./covers/ResponsibilityIsTheKey.webp'),
  RoseGlasses: require('./covers/RoseGlasses.webp'),
  SeaLily: require('./covers/SeaLily.webp'),
  SlowDownSeal: require('./covers/SlowDownSeal.webp'),
  Star: require('./covers/Star.webp'),
  Stegosaur: require('./covers/Stegosaur.webp'),
  ThankingTheClouds: require('./covers/ThankingTheClouds.webp'),
  ThatWillDo: require('./covers/ThatWillDo.webp'),
  TheAutumnContest: require('./covers/TheAutumnContest.webp'),
  TheBeautifulWeb: require('./covers/TheBeautifulWeb.webp'),
  TheBeeSavesTheHive: require('./covers/TheBeeSavesTheHive.webp'),
  TheBestTeacher: require('./covers/TheBestTeacher.webp'),
  TheBigConcertRescue: require('./covers/TheBigConcertRescue.webp'),
  TheBigWideWorld: require('./covers/TheBigWideWorld.webp'),
  TheBirthdayParty: require('./covers/TheBirthdayParty.webp'),
  TheBirthdayPresent: require('./covers/TheBirthdayPresent.webp'),
  TheBoastingBugs: require('./covers/TheBoastingBugs.webp'),
  TheCoolestDragon: require('./covers/TheCoolestDragon.webp'),
  TheDeepSeaFestival: require('./covers/TheDeepSeaFestival.webp'),
  TheDinoWhoCheatedAtTag: require('./covers/TheDinoWhoCheatedAtTag.webp'),
  TheElixirOfHealth: require('./covers/TheElixirOfHealth.webp'),
  TheFairyWhoFlewTooFast: require('./covers/TheFairyWhoFlewTooFast.webp'),
  TheFinding: require('./covers/TheFinding.webp'),
  TheGreedyBee: require('./covers/TheGreedyBee.webp'),
  TheHungriestHare: require('./covers/TheHungriestHare.webp'),
  TheJoyfulLamb: require('./covers/TheJoyfulLamb.webp'),
  TheLittleAstronaut: require('./covers/TheLittleAstronaut.webp'),
  TheLittleBearCub: require('./covers/TheLittleBearCub.webp'),
  ThePurpleSparrow: require('./covers/ThePurpleSparrow.webp'),
  TheSecretToAGoodHeart: require('./covers/TheSecretToAGoodHeart.webp'),
  TheSelfishKitty: require('./covers/TheSelfishKitty.webp'),
  TheSheepIsLost: require('./covers/TheSheepIsLost.webp'),
  TheShiveringCat: require('./covers/TheShiveringCat.webp'),
  TheSpikedChampion: require('./covers/TheSpikedChampion.webp'),
  TheSpiritOfChristmas: require('./covers/TheSpiritOfChristmas.webp'),
  TheTrappedFirefly: require('./covers/TheTrappedFirefly.webp'),
  TheTrickiestFox: require('./covers/TheTrickiestFox.webp'),
  TooManyPainters: require('./covers/TooManyPainters.webp'),
  VeggiesAreYummy: require('./covers/VeggiesAreYummy.webp'),
  WhatDoCloudsTasteLike: require('./covers/WhatDoCloudsTasteLike.webp'),
  WhenYouNeedAHelpingHand: require('./covers/WhenYouNeedAHelpingHand.webp'),
  WhereIsMyRoar: require('./covers/WhereIsMyRoar.webp'),
  WhereTheClouds: require('./covers/WhereTheClouds.webp'),
};

/**
 * Get the bundled cover image source for a book.
 * Returns a require() result usable in <Image source={...} />
 */
export function getBookCover(folderName: string): number | undefined {
  return covers[folderName];
}
